version: '3.1'

services:
  web:
    image: nginx
    ports:
      - 127.0.0.1:3005:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html
    networks:
        - web
networks:
    web:

# volumes:
  # files-data:
    #- source: ./files
